### ISSUE TITLE
pip3 installation does not work with pure Ubuntu 18.04 = Bionic

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_tesserocr#91]
trying to install ocr-d with `pip3 install ocrd_tesserocr` using Ubuntu 18.04 = Bionic Beaver leads to the following error message:

```
...
  Failed building wheel for tesserocr
  Running setup.py clean for tesserocr
  Running setup.py bdist_wheel for bagit ... done
  Stored in directory: /root/.cache/pip/wheels/8d/77/f7/8f91043ef3c99bbab558f578d19ce5938896e37e57609f9786
  Running setup.py bdist_wheel for wrapt ... done
  Stored in directory: /root/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built bagit wrapt
Failed to build tesserocr
Installing collected packages: lxml, numpy, Pillow, ocrd-utils, ocrd-models, bagit, bagit-profile, ocrd-modelfactory, ocrd-validators, wrapt, Deprecated, atomicwrites, Jinja2, itsdangerous, Werkzeug, Flask, opencv-python-headless, ocrd, tesserocr, ocrd-tesserocr
  Found existing installation: Jinja2 2.10
    Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for tesserocr ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0u0i5oh5/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5ui7pzc-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.0.0
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67108864}}
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
    tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_16PyResultIterator_8GetBestLSTMSymbolChoices(__pyx_obj_9tesserocr_PyResultIterator*)’:
    tesserocr.cpp:12198:43: error: ‘class tesseract::ResultIterator’ has no member named ‘GetBestLSTMSymbolChoices’
       __pyx_v_output = (__pyx_v_self->_riter->GetBestLSTMSymbolChoices()[0]);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
   
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0u0i5oh5/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5ui7pzc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0u0i5oh5/tesserocr/
```

@kba did email to me, that tesseract-lib in 18.04 is too old and that the docker container are based on Ubuntu 19.10.

```sh
root@Ubuntu_18.04:/home/jb# pkg-config --modversion  tesseract
4.0.0-beta.1
```

**Comment by jbarth-ubhd** [comment]
Checked yesterday: `pip3 install ocrd_tesserocr` does work with Ubuntu 19.10

**Comment by stweil** [comment]
Hi @jbarth-ubhd, there exist newer packages of `tesseract-ocr` (and the related development package) for Ubuntu. See the README.md for https://github.com/OCR-D/ocrd_tesserocr which was updated yesterday with all relevant information.

**Comment by stweil** [comment]
Maybe my [ocrd_all](https://github.com/stweil/ocrd_all) can help you with the installation. Ideally you just have to run `make all` to get everything installed. If that fails, `make all -k` should at least install most modules.

**Comment by jbarth-ubhd** [comment]
Thank you very much.
