### ISSUE TITLE
pip install ocrd_tesserocr fails with tesseract  version 4.0.0-beta-26-gfd49

### ISSUE THREAD

**Issue by finkf** [OCR-D/ocrd_tesserocr#28]
I use `pip install ocrd_tesserocr` to install ocrd_tesseract into my virtualenv environment. The installation fails with:
```
...
  Running setup.py bdist_wheel for tesserocr ... error
  Complete output from command /run/media/flo/a57ed1c0-7fc5-41b1-a6e5-0d43b3ae6a40/data/devel/work/cis-ocrd-py/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-k_dgo547/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-q7mozwr8 --python-tag cp37:
  Supporting tesseract v4.0.0
  Configs from pkg-config: {'include_dirs': ['/usr/include'], 'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67108864}}
  running bdist_wheel
  running build
  running build_ext
  building 'tesserocr' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include -I/usr/include/python3.7m -c tesserocr.cpp -o build/temp.linux-x86_64-3.7/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
  tesserocr.cpp: In function 'PyObject* __pyx_pf_9tesserocr_16PyResultIterator_8GetBestLSTMSymbolChoices(__pyx_obj_9tesserocr_PyResultIterator*)':
  tesserocr.cpp:12196:43: error: 'class tesseract::ResultIterator' has no member named 'GetBestLSTMSymbolChoices'
     __pyx_v_output = (__pyx_v_self->_riter->GetBestLSTMSymbolChoices()[0]);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for tesserocr
  Running setup.py clean for tesserocr
Failed to build tesserocr
Installing collected packages: tesserocr, ocrd-tesserocr
  Running setup.py install for tesserocr ... error
    Complete output from command /run/media/flo/a57ed1c0-7fc5-41b1-a6e5-0d43b3ae6a40/data/devel/work/cis-ocrd-py/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-k_dgo547/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fc87h61b/install-record.txt --single-version-externally-managed --compile --install-headers /run/media/flo/a57ed1c0-7fc5-41b1-a6e5-0d43b3ae6a40/data/devel/work/cis-ocrd-py/env/include/site/python3.7/tesserocr:
    Supporting tesseract v4.0.0
    Configs from pkg-config: {'include_dirs': ['/usr/include'], 'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67108864}}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include -I/usr/include/python3.7m -c tesserocr.cpp -o build/temp.linux-x86_64-3.7/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
    tesserocr.cpp: In function 'PyObject* __pyx_pf_9tesserocr_16PyResultIterator_8GetBestLSTMSymbolChoices(__pyx_obj_9tesserocr_PyResultIterator*)':
    tesserocr.cpp:12196:43: error: 'class tesseract::ResultIterator' has no member named 'GetBestLSTMSymbolChoices'
       __pyx_v_output = (__pyx_v_self->_riter->GetBestLSTMSymbolChoices()[0]);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
...
```

tesseract is installed on the system:
```tesseract -v
tesseract 4.0.0-beta.4-26-gfd49
 leptonica-1.77.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.1) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.1
 Found AVX
 Found SSE
```

**Comment by finkf** [comment]
OK. Thanks

**Comment by finkf** [comment]
It does not work for `tesseract-v4.0.0-beta.1` as well (its the default version for tesseract in ubuntu for windows).

**Comment by wrznr** [comment]
I stumbled upon the same issue: tesserocr from github does not work with tesseract from ubuntu (18.04) due to the missing LSTM choice iterator. I had to install tesseract **and** ocrd_tesserocr from github to make it work.

**Comment by finkf** [comment]
It worked for me now. I just had to use an older version for tesserocr: `pip install tesserocr==2.3.1`. Thanks.

**Comment by stweil** [comment]
Noah had updated the Python code to autodetect the Tesseract version to select the right API. It looks like ocrd_tesserocr still needs that update. Cc @noahmetzger.

**Comment by finkf** [comment]
The version downgrade of tesserocr worked for me. 
I have currently no Ubuntu machines available. Only SUSE, Ubuntu on Windows and Arch-Linux (it did not work for any of them).
Is the newer version of tesserocr stricly needed?

**Comment by kba** [comment]
@noahmetzger Can you investigate?

**Comment by noahmetzger** [comment]
I ve tried to reproduce your problem with a virtualbox Ubuntu 18.04 and the default version of tesseract, tesserocr and ocrd_tesserocr of ubuntu. 
But the for me the installation went fine.
Which version of pip and python did you use?

**Comment by kba** [comment]
@noahmetzger What version of tesserocr are you using?

```
pip freeze |grep tess
```

**Comment by noahmetzger** [comment]
2.4

**Comment by noahmetzger** [comment]
My steps were:
- Building a new Ubuntu 18.04 with virtual box
- Install pip with `sudo apt install python3-pip`
- Install virtualenv `sudo apt install virtualenv`
-create and start a virtual Environment with:
`mkdir virtualEnvironment`
`virtualenv -p python3 virtualEnvironment`
`source virtualEnvironment/bin/activate`
- Install tesseract
`sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config`
- And finally `pip3 install ocrd_tesserocr`

**Comment by wrznr** [comment]
I can confirm that the instructions by @noahmetzger work. If @finkf has a running system again, I'd propose to close this issue.

**Comment by finkf** [comment]
I have not tried it. But if it works you can close.
